### ISSUE TITLE
Slowdown

### ISSUE THREAD

**Issue by CyGrey009** [Solybum/PSOBBMod-Addons#60] opened 2023-01-27 03:43 UTC
Hi,

Been attempting to get the addons working properly but nothing I've done so far has been full-proof. I've tried everything from giving the add-ons and PSOBB exclusions from my anti-virus to outright disabling my anti-virus. I've noticed the slowdown seems to occur and even intensify when I open up my web browser Firefox on the side. I've tried with and without Firefox open and the improvement with the latter is noticeable. My PC setup is16GB of RAM, a Ryzen 5 3600, and a GTX 1060 which is more than enough to run PSOBB multiple times over.

**Comment by Solybum** [comment] 2023-01-27 05:22
I think we had some performance issues before but were solved (or at least improved a bit).

Any chance you can try to isolate which addon causes the performance issues?
Remove all addons (leave solylib as that's only used by the rest of the addons) and add one by one to see if the issue is caused by one, or if all of them cause slowdown.

If you do, make sure you also remove other addons that are not core ones, and test those as well.

**Comment by CyGrey009** [comment] 2023-01-27 07:09
Seems to happen just from me copying over the addon folder and dinput8 files.

**Comment by Solybum** [comment] 2023-01-27 07:12
Without any of the 3rd party addons?
What folders do you have in the addons folder when it causes performance issues?

**Comment by CyGrey009** [comment] 2023-01-27 09:38
It seems I was mistaken and having the main menu open caused the slowdown without any 3rd party addons. Once I closed the main menu things were pretty much fine.
I have my addons installed in User>Ephinea>addons. Also you'll have to excuse the slowness but it's late here and I didn't anticipate you'd respond so soon.
I went and tested the most up to date version of the bbmod.zip files with no 3rd party addons and there were no slowdowns. Tried just the XP bar addon and I noticed dips but nothing terrible enough to cause it to feel unplayable. Then I tried with the Player Reader for a full run of TTF with about the same results as the XP bar addon. Finally I tried the Player Reader and Item Reader and that's when the dips got more noticeable. It got even worse once I tabbed into Firefox to check something out. I'm not sure how my browser is causing the issue if it even is . I can test further with another browser but it'll have to be when I wake up as it's nearing 4am where I'm at. 

If you're on the Ephinea discord and wanted to see then I can also show you directly. I was also streaming it on my Twitch @Grey009_ and at the beginning of both of my PSO streams the slowdown happened as well.

**Comment by Solybum** [comment] 2023-01-27 18:12
I'll see if Ender can look into this a bit because I have 0 performance issues, not sure if the recent changes in Ephinea regarding rendering could be affecting this in some way.

**Comment by Elixir70** [comment] 2023-01-27 18:28
@CyGrey009 When the slowdown happens, do you have anything in the Log addon? 

What are your settings in the Ephinea launcher? Is it possible you're running this at HSAA or SSAA at a high level and your PC just can't handle it? Even though it's an old game, SSAA and HSAA at high levels can still cause some slowdown. Try going to a stock Direct3D 8 setting with no Anti-aliasing and no AF. The plugin is really lightweight these days.

**Comment by CyGrey009** [comment] 2023-01-27 22:10
> @CyGrey009 When the slowdown happens, do you have anything in the Log addon?
> 
> What are your settings in the Ephinea launcher? Is it possible you're running this at HSAA or SSAA at a high level and your PC just can't handle it? Even though it's an old game, SSAA and HSAA at high levels can still cause some slowdown. Try going to a stock Direct3D 8 setting with no Anti-aliasing and no AF. The plugin is really lightweight these days.

Yeah, seems going to D3D8 and turning off AA and filters seems to have fixed it. IIRC, my original settings were SMAA and D3D11 with some of the other graphical settings turned on such as bloom. From task manager there was no indication my GPU, CPU, or RAM were maxed out at any point even while recording/streaming the game. Is it possible there's a compatibility issue there?

**Comment by Elixir70** [comment] 2023-01-27 22:42
@CyGrey009 No compatibility issue. PSOBB originally had only D3D8 as a renderer. Ephinea added D3D9, 11, 12, 9on12, and Vulkan in the past year. There's no guarantee about performance for the various renderers--the only guarantee is that leaving the client set in D3D8 will give you the original renderer. And for some people, some of the new renderers can crash at startup. 

PSOBB rendering through D3D11 just performs badly for some people whether through the Ephinea client or through external dgVoodoo. Oddly enough, D3D12 performs just fine. I suggest you keep experimenting with the rendering options, or at least try D3D9 and re-enable AA+SMAA. It'll probably perform just fine with addons again.

**Comment by CyGrey009** [comment] 2023-01-28 04:50
@Elixir70 
Had no clue the renders were new additions at this point. I should've tested each render but I kept defaulting to the issue  being my anti-virus or another program conflicting with the client. Also after some more playtime I've found D3D8 and even D3D12 work perfectly alongside the addons as you said. I appreciate both you and Soly helping me fix the issue.

**Comment by Solybum** [comment] 2023-02-01 14:01
I'll be closing the issue since it's related to those renderers ephinea is using.

**Closed by Solybum** 2023-02-01 14:01 UTC
